export const sampleShloka = {
  chapter: 2, verse: 47,
  sanskrit: 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन |\nमा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि ||',
  transliteration: "karmaṇy-evādhikāras te mā phaleṣu kadācana |\nmā karma-phala-hetur bhūr mā te saṅgo 'stv akarmaṇi ||",
  english: "You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions. Never consider yourself the cause of results, nor be attached to inaction.",
};

export const chapters = [
  { id: 1,  chapter_number: 1,  verses_count: 47,  name: 'Arjuna Vishada Yoga',             sanskritName: 'अर्जुनविषादयोग',              translation: 'The Distress of Arjuna',           summary: 'Arjuna, overwhelmed by grief and moral conflict on the battlefield, surrenders to Krishna for guidance.',                                      image: '/images/chapters/ch1.png',  pos: 'center top' },
  { id: 2,  chapter_number: 2,  verses_count: 72,  name: 'Sankhya Yoga',                    sanskritName: 'सांख्ययोग',                    translation: 'The Yoga of Knowledge',            summary: 'Krishna summarizes the entire wisdom of the Gita, explaining the eternal nature of the soul and selfless duty.',                                image: '/images/chapters/ch2.png',  pos: 'center 20%' },
  { id: 3,  chapter_number: 3,  verses_count: 43,  name: 'Karma Yoga',                      sanskritName: 'कर्मयोग',                      translation: 'The Yoga of Action',               summary: 'The science of selfless service, teaching how to act in the material world without generating karma.',                                          image: '/images/chapters/ch3.png',  pos: 'center 30%' },
  { id: 4,  chapter_number: 4,  verses_count: 42,  name: 'Jnana Karma Sannyasa Yoga',       sanskritName: 'ज्ञानकर्मसंन्यासयोग',         translation: 'The Yoga of Knowledge & Action',  summary: 'Krishna reveals the path of eternal wisdom, the purpose of divine avatars, and the nature of sacrifice.',                                       image: '/images/chapters/ch4.png',  pos: 'center top' },
  { id: 5,  chapter_number: 5,  verses_count: 29,  name: 'Karma Sannyasa Yoga',             sanskritName: 'कर्मसंन्यासयोग',              translation: 'The Yoga of Renunciation',         summary: 'A deep comparison between dry renunciation of action and acting in devotion. Devotion is shown to be superior.',                                image: '/images/chapters/ch5.png',  pos: 'center 25%' },
  { id: 6,  chapter_number: 6,  verses_count: 47,  name: 'Dhyana Yoga',                     sanskritName: 'ध्यानयोग',                     translation: 'The Yoga of Meditation',           summary: 'Krishna explains the practice of yoga, mind control, and meditation techniques to attain connection with the soul.',                              image: '/images/chapters/ch6.png',  pos: 'center 20%' },
  { id: 7,  chapter_number: 7,  verses_count: 30,  name: 'Jnana Vijnana Yoga',              sanskritName: 'ज्ञानविज्ञानयोग',             translation: 'The Yoga of Wisdom & Realization', summary: 'Krishna teaches how the material and spiritual energies combine to form all creation, and how to know him.',                                     image: '/images/chapters/ch7.png',  pos: 'center 35%' },
  { id: 8,  chapter_number: 8,  verses_count: 28,  name: 'Akshara Brahma Yoga',             sanskritName: 'अक्षरब्रह्मयोग',              translation: 'The Yoga of the Imperishable',     summary: 'Explains the ultimate destiny of the soul, how to achieve the supreme state, and the power of remembering Krishna at death.',                    image: '/images/chapters/ch8.png',  pos: 'center 30%' },
  { id: 9,  chapter_number: 9,  verses_count: 34,  name: 'Raja Vidya Raja Guhya Yoga',      sanskritName: 'राजविद्याराजगुह्ययोग',         translation: 'The Sovereign Science & Secret',   summary: 'Reveals the supreme mystery of divine presence, devotion, and the absolute power of surrender.',                                                 image: '/images/chapters/ch9.png',  pos: 'center 20%' },
  { id: 10, chapter_number: 10, verses_count: 42,  name: 'Vibhuti Yoga',                    sanskritName: 'विभूतियोग',                    translation: 'The Yoga of Divine Glories',       summary: 'Krishna describes his primary infinite forms, powers, and manifestations throughout creation.',                                                   image: '/images/chapters/ch10.png', pos: 'center top' },
  { id: 11, chapter_number: 11, verses_count: 55,  name: 'Vishvarupa Darshana Yoga',        sanskritName: 'विश्वरूपदर्शनयोग',            translation: 'The Yoga of the Cosmic Form',      summary: 'Arjuna beholds the spectacular, terrifying cosmic form (Vishwaroopam) of Krishna containing all universes.',                                    image: '/images/chapters/ch11.png', pos: 'center 35%' },
  { id: 12, chapter_number: 12, verses_count: 20,  name: 'Bhakti Yoga',                     sanskritName: 'भक्तियोग',                     translation: 'The Yoga of Devotion',             summary: 'The ultimate path of pure devotion, loving service, and the qualities of a devotee dear to the Lord.',                                           image: '/images/chapters/ch12.png', pos: 'center 20%' },
  { id: 13, chapter_number: 13, verses_count: 35,  name: 'Kshetra Kshetrajna Vibhaga Yoga', sanskritName: 'क्षेत्रक्षेत्रज्ञविभागयोग',  translation: 'The Knower & The Field',           summary: 'The distinction between the physical body (field), the individual soul (knower), and the Supersoul.',                                            image: '/images/chapters/ch13.png', pos: 'center 30%' },
  { id: 14, chapter_number: 14, verses_count: 27,  name: 'Gunatraya Vibhaga Yoga',          sanskritName: 'गुणत्रयविभागयोग',             translation: 'The Three Modes of Nature',        summary: 'Krishna details the three gunas (modes): goodness, passion, and ignorance, and how to transcend them.',                                          image: '/images/chapters/ch14.png', pos: 'center 30%' },
  { id: 15, chapter_number: 15, verses_count: 20,  name: 'Purushottama Yoga',               sanskritName: 'पुरुषोत्तमयोग',               translation: 'The Supreme Divine Person',        summary: 'The allegory of the inverted Banyan tree representing material existence, and description of the Supreme Self.',                                  image: '/images/chapters/ch15.png', pos: 'center 20%' },
  { id: 16, chapter_number: 16, verses_count: 24,  name: 'Daivasura Sampad Vibhaga Yoga',   sanskritName: 'दैवासुरसम्पद्विभागयोग',       translation: 'The Divine & Demonic Natures',     summary: 'An exploration of virtues leading to liberation and vices leading to material bondage.',                                                          image: '/images/chapters/ch16.png', pos: 'center top' },
  { id: 17, chapter_number: 17, verses_count: 28,  name: 'Shraddhatraya Vibhaga Yoga',      sanskritName: 'श्रद्धात्रयविभागयोग',         translation: 'The Threefold Divisions of Faith', summary: 'How faith, food, sacrifice, austerity, and charity are categorised according to the three gunas.',                                                image: '/images/chapters/ch17.png', pos: 'center 25%' },
  { id: 18, chapter_number: 18, verses_count: 78,  name: 'Moksha Sannyasa Yoga',            sanskritName: 'मोक्षसंन्यासयोग',             translation: 'The Yoga of Liberation',           summary: 'The grand conclusion of the Gita, summarizing all spiritual paths and teaching total surrender to Krishna.',                                      image: '/images/chapters/ch18.png', pos: 'center 30%' },
];
